// Fonts that ship with a standard Microsoft Office / Windows install.
// These are system fonts rendered directly by the OS — nothing is bundled or
// downloaded, so a font only displays correctly if it's actually installed.
// "Common" fonts are shown first in the picker since they're the ones users
// reach for most; the full list covers the rest of Office's font set.

export const COMMON_FONTS = [
  'Calibri',
  'Cambria',
  'Segoe UI',
  'Arial',
  'Times New Roman',
  'Georgia',
  'Verdana',
  'Tahoma',
  'Trebuchet MS',
  'Courier New',
  'Comic Sans MS',
  'Garamond'
]

export const ALL_OFFICE_FONTS = [
  'Algerian',
  'Arial',
  'Arial Black',
  'Bahnschrift',
  'Baskerville Old Face',
  'Bell MT',
  'Bernard MT Condensed',
  'Blackadder ITC',
  'Bodoni MT',
  'Book Antiqua',
  'Bookman Old Style',
  'Bradley Hand ITC',
  'Britannic Bold',
  'Broadway',
  'Brush Script MT',
  'Calibri',
  'Californian FB',
  'Calisto MT',
  'Cambria',
  'Candara',
  'Castellar',
  'Centaur',
  'Century',
  'Century Gothic',
  'Chiller',
  'Colonna MT',
  'Comic Sans MS',
  'Consolas',
  'Constantia',
  'Cooper Black',
  'Copperplate Gothic Bold',
  'Copperplate Gothic Light',
  'Corbel',
  'Courier New',
  'Curlz MT',
  'Edwardian Script ITC',
  'Elephant',
  'Engravers MT',
  'Eras Bold ITC',
  'Eras Demi ITC',
  'Eras Light ITC',
  'Eras Medium ITC',
  'Felix Titling',
  'Footlight MT Light',
  'Forte',
  'Franklin Gothic Book',
  'Franklin Gothic Medium',
  'Freestyle Script',
  'French Script MT',
  'Gabriola',
  'Gadugi',
  'Garamond',
  'Georgia',
  'Gigi',
  'Gill Sans MT',
  'Gloucester MT Extra Condensed',
  'Goudy Old Style',
  'Goudy Stout',
  'Haettenschweiler',
  'Harlow Solid Italic',
  'Harrington',
  'High Tower Text',
  'Impact',
  'Imprint MT Shadow',
  'Informal Roman',
  'Jokerman',
  'Juice ITC',
  'Kristen ITC',
  'Kunstler Script',
  'Lucida Bright',
  'Lucida Calligraphy',
  'Lucida Console',
  'Lucida Fax',
  'Lucida Handwriting',
  'Lucida Sans Unicode',
  'Magneto',
  'Maiandra GD',
  'Matura MT Script Capitals',
  'Mistral',
  'Modern No. 20',
  'Monotype Corsiva',
  'MS Reference Sans Serif',
  'Niagara Engraved',
  'Niagara Solid',
  'OCR A Extended',
  'Old English Text MT',
  'Onyx',
  'Palace Script MT',
  'Palatino Linotype',
  'Papyrus',
  'Parchment',
  'Perpetua',
  'Perpetua Titling MT',
  'Playbill',
  'Poor Richard',
  'Pristina',
  'Rage Italic',
  'Ravie',
  'Rockwell',
  'Rockwell Condensed',
  'Rockwell Extra Bold',
  'Script MT Bold',
  'Segoe Print',
  'Segoe Script',
  'Segoe UI',
  'Showcard Gothic',
  'Snap ITC',
  'Stencil',
  'Sylfaen',
  'Symbol',
  'Tahoma',
  'Tempus Sans ITC',
  'Times New Roman',
  'Trebuchet MS',
  'Tw Cen MT',
  'Verdana',
  'Viner Hand ITC',
  'Vivaldi',
  'Vladimir Script',
  'Wide Latin',
  'Wingdings',
  'Wingdings 2',
  'Wingdings 3'
].sort((a, b) => a.localeCompare(b))
